services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - oracle
    env_file:
      - .env
    networks:
      - my-network

  oracle:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=oracle
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - my-network

networks:
  my-network:
    external: true

volumes:
  oracle-data: